# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_shop', '0004_auto_20161222_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Профиль', to='core_shop.Profile'),
        ),
    ]
