# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_shop', '0006_auto_20161229_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product/no-img.png', upload_to='product/pictures', verbose_name='Изображение'),
        ),
    ]
