# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20170101_1841'),
        ('core_shop', '0007_auto_20161229_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Корзина', to='cart.CartItem', verbose_name='Корзина'),
        ),
    ]
